baseURL: http://localhost:1313/
title: iswai

defaultContentLanguage: en
languageCode: en-us

googleAnalytics: UA-151173516-1

contentDir: docs
enableGitInfo: true
enableInlineShortcodes: true

pygmentsCodeFences: true
pygmentsOptions: linenos=table
pygmentsUseClasses: true
pygmentsUseClassic: false

publishDir: build

disableKinds:
- taxonomy
- taxonomyTerm
- RSS
- sitemap
