#!/bin/bash
#
#   - name: Deploy
#     env:
#       PERSONAL_ACCESS_TOKEN: ${{ secrets.YOUR_SECRET_PAT }}   * required
#       PUBLISH_REPOSITORY: github_organization/project_name    * optional
#       PUBLISH_BRANCH: gh-pages                                * optional
#       PUBLISH_DIR: ./build                                    * optional
#     run: wget -O - https://raw.githubusercontent.com/iswai/docs-sdk/master/actions/gh-pages-deploy | bash
#
set -e

function print_error() {
    echo -e "\e[31mERROR: ${1}\e[m"
}

function print_info() {
    echo -e "\e[36mINFO: ${1}\e[m"
}

PUBLISH_REPOSITORY="${PUBLISH_REPOSITORY:-$GITHUB_REPOSITORY}"
PUBLISH_BRANCH="${PUBLISH_BRANCH:-gh-pages}"
PUBLISH_DIR="${PUBLISH_DIR:-./build}"
TOKEN="${PERSONAL_ACCESS_TOKEN:-$GITHUB_TOKEN}"

REMOTE_REPO="https://x-access-token:${TOKEN}@github.com/${PUBLISH_REPOSITORY}.git"

if [ -z "${TOKEN}" ]; then
    print_error "Missing env PERSONAL_ACCESS_TOKEN or GITHUB_TOKEN"
    exit 1
fi

if [ -z "${PUBLISH_REPOSITORY}" ]; then
    print_error "Missing env PUBLISH_REPOSITORY or GITHUB_REPOSITORY"
    exit 1
fi

print_info "Deploying ${PUBLISH_REPOSITORY} from ${PUBLISH_DIR} to ${PUBLISH_BRANCH}"

cd "${PUBLISH_DIR}"
#git init
#git checkout --orphan "${PUBLISH_BRANCH}"
git config user.name "${GITHUB_ACTOR}"
git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
git add --all
if [ -n "$(git status --porcelain)" ]; then
    print_info "No changes detected"
    cd ..
    exit 0
fi

print_info "Pushing changes to ${PUBLISH_BRANCH}"
git commit -m "docs: deploy from ${GITHUB_SHA}"
git push "${REMOTE_REPO}" "${PUBLISH_BRANCH}"
cd ..

print_info "${GITHUB_SHA} deployed successfully"
