name: docker-image

on:
  push:
    branches:
    - master

jobs:
  build:
    name: build docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Build the Docker container image
      run: docker build -t docker.pkg.github.com/iswai/docs-sdk/hugo:latest .

    - name: Push the image to GPR
      run: |
        docker login docker.pkg.github.com -u publisher -p "${GITHUB_PACKAGE_REGISTRY_TOKEN}"
        docker push docker.pkg.github.com/iswai/docs-sdk/hugo:latest
      env:
        GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
