name: github-pages

on:
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    name: build & deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Prepare
      run: wget -O - https://raw.githubusercontent.com/iswai/docs-sdk/master/actions/gh-pages-prepare | bash

    - name: Build
      uses: iswai/docs-sdk@master
      with:
        command: 'build'

    - name: Deploy
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.ISWAI_BOT }}
      run: wget -O - https://raw.githubusercontent.com/iswai/docs-sdk/master/actions/gh-pages-deploy | bash
