name: github-pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Build
      uses: docker://iswai/iswai-docs:latest
      with:
        args: 'build'

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./build
